---
names:
  dashboard: Test Driven Development Dashboard
  watcher: TDDD - Watcher
  worker: TDDD - Worker
url_prefixes:
  global: ''
  dashboard: ''
  tests: "/tests"
  projects: "/projects"
  files: "/files"
regex_file_matcher: "/([A-Za-z0-9\\/._-]+)(?::| on line )([1-9][0-9]*)/"
poll_interval: 300
tee: "/usr/bin/tee"
script: "/usr/bin/script -q %s %s"
tmp: "/var/tmp/"
show_progress: false
